# Railway Configuration
[build]
provider = "nixpacks"

[deploy]
buildCommand = "pip install -r requirements.txt"
startCommand = "gunicorn railway_start:app --bind 0.0.0.0:$PORT"

[env]
PYTHON_VERSION = "3.11.0"
